services:
  microservice-template_postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-template

  microservice-template_mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data:/data/db
    networks:
      - microservice-template

  microservice-template:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_URL=microservice-template_postgres
      - MONGO_URL=microservice-template_mongo
    depends_on:
      microservice-template_postgres:
        condition: service_healthy
      microservice-template_mongo:
        condition: service_healthy
    tty: true
    networks:
      - microservice-template
      - control-room_backend
    labels:
      - "traefik.http.routers.microservice-template.rule=HostRegexp(`api\..+`) && PathPrefix(`/microservice`)"


networks:
  microservice-template:
  control-room_backend:
    external: true

volumes:
  postgres-data:
  mongo-data: