services:
  category-service_neo4j:
    image: neo4j:2025.02-community-bullseye
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_server_directories_import: '/'
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./categories.csv:/categories.csv
      - neo4j-logs:/logs
    networks:
      - category-service
      - backend
    labels:
      - "traefik.http.routers.category-service_neo4j.rule=HostRegexp(`neo4j\\..+`) && PathPrefix(`/category`)"



  category-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_URL: category-service_postgres
      MONGO_DB: mongo
      MONGO_URL: category-service_mongo
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      elasticsearch:
        condition: service_healthy
      category-service_neo4j:
        condition: service_healthy
#      category-service_mongo:
#        condition: service_healthy
    volumes:
      - .:/category-service
    tty: true
    networks:
      - category-service
      - backend
      - analytics
    labels:
      - "traefik.http.routers.category-service.rule=HostRegexp(`api\\..+`) && PathPrefix(`/category`)"

networks:
  category-service:
volumes:
  postgres-data:
  mongo-data:
  neo4j-logs:
