services:
  category-service_neo4j:
    image: neo4j:2025.02-community-bullseye
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_server_directories_import: '/'
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./categories.csv:/categories.csv
      - category-neo4j-logs:/logs
    networks:
      - category-service
      - backend
    labels:
      - "traefik.http.routers.category-service_neo4j.rule=HostRegexp(`neo4j-category\\..+`)"
      - "traefik.http.routers.category-service_neo4j.service=category-service_neo4j"
      - "traefik.http.services.category-service_neo4j.loadbalancer.server.port=7474"
      - "traefik.http.routers.category-service_neo4j_bolt.rule=HostRegexp(`neo4j-category\\..+`) && PathPrefix(`/bolt`)"
      - "traefik.http.routers.category-service_neo4j_bolt.service=category-service_neo4j_bolt"
      - "traefik.http.services.category-service_neo4j_bolt.loadbalancer.server.port=7687"


  category-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_URL: category-service_postgres
      MONGO_DB: mongo
      MONGO_URL: category-service_mongo
      NEO4J_URL: bolt://category-service_neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      category-service_neo4j:
        condition: service_healthy
    volumes:
      - /category-service/.venv
      - .:/category-service
    tty: true
    networks:
      - category-service
      - backend
      - analytics
    labels:
      - "traefik.http.routers.category-service.rule=HostRegexp(`api-debug\\..+`) && PathPrefix(`/category`)"

networks:
  category-service:
volumes:
  category-neo4j-logs:
