
# This code in only template, CHANGE IT!
# The ports are only declarative, YOU CAN'T UNCOMMENT THEM
services:
  serviceName_postgres: #change here the name for serviceName_db if needed
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
#    ports:
#      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - serviceName

  serviceName_mongo: #change here the name for serviceName_document if needed
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 10s
      retries: 5
#    ports:
#      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - serviceName

  serviceName: #change here the name for serviceName
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    depends_on:
      serviceName_postgres:
        condition: service_healthy
      serviceName_mongo:
        condition: service_healthy
#    ports:
#      - "8000:8000" # change me
    tty: true
    networks:
      - serviceName
      - backend
    labels:
      - "traefik.http.routers.serviceName.rule=Host(`serviceName.localhost`)"

networks:
  serviceName:
