services:
  category-service_neo4j:
    image: neo4j:2025.02-community-bullseye
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_server_directories_import: '/'
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./categories.csv:/categories.csv
      - category-neo4j-logs:/logs
    networks:
      - category-service

  category-service:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      NEO4J_URL: bolt://category-service_neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      category-service_neo4j:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    #      category-service_mongo:
    #        condition: service_healthy
    tty: true
    networks:
      - category-service
      - backend
      - analytics

networks:
  category-service:

volumes:
  category-neo4j-logs: